# Theme Configuration
# To switch themes, change the path below to another theme file in themes/
[general]
import = [
  "themes/catppuccin_latte.toml"
]

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 300

[env]
title = "Alacritty"

[font]
size = 12

[font.bold]
family = "JetBrains Mono"
style = "Regular"

[font.glyph_offset]
x = 1
y = 1

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Thin Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.offset]
x = 1
y = 2

[scrolling]
history = 5000
multiplier = 3

[window]
dynamic_title = true
opacity = 0.99

[window.padding]
x = 2
y = 2

